### ISSUE TITLE
error: method fdeChangePassword in interface IVold cannot be applied to given types;

### ISSUE THREAD

**Issue by AToMiXhawK** [BootleggersROM/system_vold#1]
[ 99% 90931/91477] //frameworks/base/services/core:services.core.unboosted javac [common]
FAILED: /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar 
rm -rf "/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && mkdir -p "/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && /home/lightsail/android/bootleggers_4.0/out/soong/host/linux-x86/bin/zipsync -d /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars -l /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list -f "*.java"  && /home/lightsail/android/bootleggers_4.0/out/soong/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk9/linux-x86/bin/javac -J-Xmx2048M -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -bootclasspath /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/libcore/core-oj/android_common/turbine-combined/core-oj.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/libcore/core-libart/android_common/turbine-combined/core-libart.jar -classpath /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/external/okhttp/okhttp/android_common/turbine-jarjar/okhttp.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/net/services.net/android_common/turbine-combined/services.net.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/light/2.0/android.hardware.light-V2.0-java/android_common/turbine-combined/android.hardware.light-V2.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/power/1.0/android.hardware.power-V1.0-java/android_common/turbine-combined/android.hardware.power-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/tv/cec/1.0/android.hardware.tv.cec-V1.0-java/android_common/turbine-combined/android.hardware.tv.cec-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager-V1.0-java/android_common/turbine-combined/android.hidl.manager-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/system/timezone/distro/core/time_zone_distro/android_common/turbine-combined/time_zone_distro.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/system/timezone/distro/installer/time_zone_distro_installer/android_common/turbine-combined/time_zone_distro_installer.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/authsecret/1.0/android.hardware.authsecret-V1.0-java/android_common/turbine-combined/android.hardware.authsecret-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/broadcastradio/2.0/android.hardware.broadcastradio-V2.0-java/android_common/turbine-combined/android.hardware.broadcastradio-V2.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/health/1.0/android.hardware.health-V1.0-java/android_common/turbine-combined/android.hardware.health-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/health/2.0/android.hardware.health-V2.0-java/android_common/turbine-combined/android.hardware.health-V2.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/weaver/1.0/android.hardware.weaver-V1.0-java/android_common/turbine-combined/android.hardware.weaver-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.1/android.hardware.biometrics.fingerprint-V2.1-java/android_common/turbine-combined/android.hardware.biometrics.fingerprint-V2.1-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/oemlock/1.0/android.hardware.oemlock-V1.0-java/android_common/turbine-combined/android.hardware.oemlock-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/tetheroffload/control/1.0/android.hardware.tetheroffload.control-V1.0-java/android_common/turbine-combined/android.hardware.tetheroffload.control-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/vibrator/1.0/android.hardware.vibrator-V1.0-java/android_common/turbine-combined/android.hardware.vibrator-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/configstore/1.0/android.hardware.configstore-V1.0-java/android_common/turbine-combined/android.hardware.configstore-V1.0-java.jar:/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/hardware/interfaces/contexthub/1.0/android.hardware.contexthub-V1.0-java/android_common/turbine-combined/android.hardware.contexthub-V1.0-java.jar -source 1.8 -target 1.8 -d /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -s /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno @/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp @/home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list && /home/lightsail/android/bootleggers_4.0/out/soong/host/linux-x86/bin/soong_zip -jar -o /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar -C /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -D /home/lightsail/android/bootleggers_4.0/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2319: error: method fdeChangePassword in interface IVold cannot be applied to given types;
            mVold.fdeChangePassword(type, password);
                 ^
  required: int,String,String
  found: int,String
  reason: actual and formal argument lists differ in length
1 error

**Comment by notakbuzz** [comment]
@AToMiXhawK how u fixed?

**Comment by AToMiXhawK** [comment]
> @AToMiXhawK how u fixed?

It a long while back that i don't even remember it.

**Comment by Itsyadavishal** [comment]
> 

You faced same error na , got solution ?
